GET https://finance.yahoo.com/quote/PYPL/history/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36

###
GET https://finance.yahoo.com/quote/PYPL/history/?.neo_opt=

###
POST http://localhost:8383/api
Content-Type: application/json

{
    "stock_ticker": "pypl"
}